# Generated by Django 5.0.4 on 2024-05-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='condition',
            new_name='operational',
        ),
        migrations.AlterField(
            model_name='food',
            name='max_price',
            field=models.CharField(choices=[('Rp100.000,-', 'Rp100.000,-'), ('Rp200.000,-', 'Rp200.000,-'), ('Rp500.000,-', 'Rp500.000,-'), ('Rp750.000,-', 'Rp750.000,-'), ('Rp1000.000,-', 'Rp1000.000,-')], max_length=20),
        ),
    ]
