# Generated by Django 5.0.4 on 2024-05-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_rename_condition_food_operational_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='operational',
        ),
        migrations.AddField(
            model_name='food',
            name='operational_day',
            field=models.CharField(choices=[('Senin - Minggu', 'Senin - Minggu'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Senin - Minggu', max_length=40),
        ),
        migrations.AddField(
            model_name='food',
            name='operational_hour',
            field=models.CharField(choices=[('08:00 - 16:00 WIB', '08:00 - 16:00 WIB'), ('08:00 - 22:00 WIB', '08:00 - 22:00 WIB'), ('09:00 - 16:00 WIB', '09:00 - 16:00 WIB'), ('09:00 - 22:00 WIB', '09:00 - 22:00 WIB'), ('10:00 - 22:00 WIB', '10:00 - 22:00 WIB'), ('13:00 - 22:00 WIB', '13:00 - 22:00 WIB'), ('24 Hour', '24 Hour')], default='08:00 - 22:00 WIB', max_length=40),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
