# Generated by Django 5.0.4 on 2024-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_remove_food_operational_food_operational_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
