# Generated by Django 5.0.4 on 2024-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0004_alter_food_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('operational_hour', models.CharField(choices=[('08:00 - 16:00 WIB', '08:00 - 16:00 WIB'), ('08:00 - 22:00 WIB', '08:00 - 22:00 WIB'), ('09:00 - 16:00 WIB', '09:00 - 16:00 WIB'), ('09:00 - 22:00 WIB', '09:00 - 22:00 WIB'), ('10:00 - 22:00 WIB', '10:00 - 22:00 WIB'), ('13:00 - 22:00 WIB', '13:00 - 22:00 WIB'), ('24 Hour', '24 Hour')], default='08:00 - 22:00 WIB', max_length=40)),
                ('operational_day', models.CharField(choices=[('Senin - Minggu', 'Senin - Minggu'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Senin - Minggu', max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('min_price', models.CharField(choices=[('Rp20.000,-', 'Rp20.000,-'), ('Rp50.000,-', 'Rp50.000,-'), ('Rp75.000,-', 'Rp75.000,-'), ('Rp100.000,-', 'Rp100.000,-')], max_length=20)),
                ('max_price', models.CharField(choices=[('Rp100.000,-', 'Rp100.000,-'), ('Rp200.000,-', 'Rp200.000,-'), ('Rp500.000,-', 'Rp500.000,-'), ('Rp750.000,-', 'Rp750.000,-'), ('Rp1000.000,-', 'Rp1000.000,-')], max_length=20)),
                ('rating', models.CharField(max_length=4)),
                ('review', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('operational_hour', models.CharField(choices=[('08:00 - 16:00 WIB', '08:00 - 16:00 WIB'), ('08:00 - 22:00 WIB', '08:00 - 22:00 WIB'), ('09:00 - 16:00 WIB', '09:00 - 16:00 WIB'), ('09:00 - 22:00 WIB', '09:00 - 22:00 WIB'), ('10:00 - 22:00 WIB', '10:00 - 22:00 WIB'), ('13:00 - 22:00 WIB', '13:00 - 22:00 WIB'), ('24 Hour', '24 Hour')], default='08:00 - 22:00 WIB', max_length=40)),
                ('operational_day', models.CharField(choices=[('Senin - Minggu', 'Senin - Minggu'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Senin - Minggu', max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('min_price', models.CharField(choices=[('Rp20.000,-', 'Rp20.000,-'), ('Rp50.000,-', 'Rp50.000,-'), ('Rp75.000,-', 'Rp75.000,-'), ('Rp100.000,-', 'Rp100.000,-')], max_length=20)),
                ('max_price', models.CharField(choices=[('Rp100.000,-', 'Rp100.000,-'), ('Rp200.000,-', 'Rp200.000,-'), ('Rp500.000,-', 'Rp500.000,-'), ('Rp750.000,-', 'Rp750.000,-'), ('Rp1000.000,-', 'Rp1000.000,-')], max_length=20)),
                ('rating', models.CharField(max_length=4)),
                ('review', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('operational_hour', models.CharField(choices=[('08:00 - 16:00 WIB', '08:00 - 16:00 WIB'), ('08:00 - 22:00 WIB', '08:00 - 22:00 WIB'), ('09:00 - 16:00 WIB', '09:00 - 16:00 WIB'), ('09:00 - 22:00 WIB', '09:00 - 22:00 WIB'), ('10:00 - 22:00 WIB', '10:00 - 22:00 WIB'), ('13:00 - 22:00 WIB', '13:00 - 22:00 WIB'), ('24 Hour', '24 Hour')], default='08:00 - 22:00 WIB', max_length=40)),
                ('operational_day', models.CharField(choices=[('Senin - Minggu', 'Senin - Minggu'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Senin - Minggu', max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('min_price', models.CharField(choices=[('Rp20.000,-', 'Rp20.000,-'), ('Rp50.000,-', 'Rp50.000,-'), ('Rp75.000,-', 'Rp75.000,-'), ('Rp100.000,-', 'Rp100.000,-')], max_length=20)),
                ('max_price', models.CharField(choices=[('Rp100.000,-', 'Rp100.000,-'), ('Rp200.000,-', 'Rp200.000,-'), ('Rp500.000,-', 'Rp500.000,-'), ('Rp750.000,-', 'Rp750.000,-'), ('Rp1000.000,-', 'Rp1000.000,-')], max_length=20)),
                ('rating', models.CharField(max_length=4)),
                ('review', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('operational_hour', models.CharField(choices=[('08:00 - 16:00 WIB', '08:00 - 16:00 WIB'), ('08:00 - 22:00 WIB', '08:00 - 22:00 WIB'), ('09:00 - 16:00 WIB', '09:00 - 16:00 WIB'), ('09:00 - 22:00 WIB', '09:00 - 22:00 WIB'), ('10:00 - 22:00 WIB', '10:00 - 22:00 WIB'), ('13:00 - 22:00 WIB', '13:00 - 22:00 WIB'), ('24 Hour', '24 Hour')], default='08:00 - 22:00 WIB', max_length=40)),
                ('operational_day', models.CharField(choices=[('Senin - Minggu', 'Senin - Minggu'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Senin - Minggu', max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('min_price', models.CharField(choices=[('Rp20.000,-', 'Rp20.000,-'), ('Rp50.000,-', 'Rp50.000,-'), ('Rp75.000,-', 'Rp75.000,-'), ('Rp100.000,-', 'Rp100.000,-')], max_length=20)),
                ('max_price', models.CharField(choices=[('Rp100.000,-', 'Rp100.000,-'), ('Rp200.000,-', 'Rp200.000,-'), ('Rp500.000,-', 'Rp500.000,-'), ('Rp750.000,-', 'Rp750.000,-'), ('Rp1000.000,-', 'Rp1000.000,-')], max_length=20)),
                ('rating', models.CharField(max_length=4)),
                ('review', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('operational_hour', models.CharField(choices=[('08:00 - 16:00 WIB', '08:00 - 16:00 WIB'), ('08:00 - 22:00 WIB', '08:00 - 22:00 WIB'), ('09:00 - 16:00 WIB', '09:00 - 16:00 WIB'), ('09:00 - 22:00 WIB', '09:00 - 22:00 WIB'), ('10:00 - 22:00 WIB', '10:00 - 22:00 WIB'), ('13:00 - 22:00 WIB', '13:00 - 22:00 WIB'), ('24 Hour', '24 Hour')], default='08:00 - 22:00 WIB', max_length=40)),
                ('operational_day', models.CharField(choices=[('Senin - Minggu', 'Senin - Minggu'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Senin - Minggu', max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('min_price', models.CharField(choices=[('Rp20.000,-', 'Rp20.000,-'), ('Rp50.000,-', 'Rp50.000,-'), ('Rp75.000,-', 'Rp75.000,-'), ('Rp100.000,-', 'Rp100.000,-')], max_length=20)),
                ('max_price', models.CharField(choices=[('Rp100.000,-', 'Rp100.000,-'), ('Rp200.000,-', 'Rp200.000,-'), ('Rp500.000,-', 'Rp500.000,-'), ('Rp750.000,-', 'Rp750.000,-'), ('Rp1000.000,-', 'Rp1000.000,-')], max_length=20)),
                ('rating', models.CharField(max_length=4)),
                ('review', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
