# Generated by Django 5.0.4 on 2024-05-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0005_entertain_hospital_mall_shopping_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='Azhira', max_length=40)),
                ('content', models.CharField(max_length=1000)),
                ('views', models.CharField(max_length=10)),
                ('up', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CommentNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.news')),
            ],
        ),
    ]
