# Generated by Django 5.0.4 on 2024-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0006_news_commentnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
