# Generated by Django 5.0.4 on 2024-06-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0009_alter_news_up_alter_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertain',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=4),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=4),
        ),
        migrations.AddField(
            model_name='hospital',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=4),
        ),
        migrations.AddField(
            model_name='mall',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=4),
        ),
        migrations.AddField(
            model_name='shopping',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=4),
        ),
        migrations.AddField(
            model_name='sport',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=4),
        ),
        migrations.AlterField(
            model_name='entertain',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entertain',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4),
        ),
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4),
        ),
        migrations.AlterField(
            model_name='mall',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mall',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sport',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sport',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4),
        ),
    ]
