# Generated by Django 5.0.4 on 2024-06-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0010_entertain_price_food_price_hospital_price_mall_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertain',
            name='latitude',
            field=models.FloatField(blank=True, default=-6.300136),
        ),
        migrations.AddField(
            model_name='entertain',
            name='longitude',
            field=models.FloatField(blank=True, default=106.639061),
        ),
        migrations.AddField(
            model_name='food',
            name='latitude',
            field=models.FloatField(blank=True, default=-6.300136),
        ),
        migrations.AddField(
            model_name='food',
            name='longitude',
            field=models.FloatField(blank=True, default=106.639061),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, default=-6.300136),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, default=106.639061),
        ),
        migrations.AddField(
            model_name='mall',
            name='latitude',
            field=models.FloatField(blank=True, default=-6.300136),
        ),
        migrations.AddField(
            model_name='mall',
            name='longitude',
            field=models.FloatField(blank=True, default=106.639061),
        ),
        migrations.AddField(
            model_name='shopping',
            name='latitude',
            field=models.FloatField(blank=True, default=-6.300136),
        ),
        migrations.AddField(
            model_name='shopping',
            name='longitude',
            field=models.FloatField(blank=True, default=106.639061),
        ),
        migrations.AddField(
            model_name='sport',
            name='latitude',
            field=models.FloatField(blank=True, default=-6.300136),
        ),
        migrations.AddField(
            model_name='sport',
            name='longitude',
            field=models.FloatField(blank=True, default=106.639061),
        ),
    ]
