# Generated by Django 5.0.4 on 2024-06-21 10:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0012_alter_news_content_delete_commentnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
