# Generated by Django 5.0.4 on 2024-06-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0015_busroute_halte_busschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halte',
            options={'ordering': ['nama_halte']},
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='rute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rute', to='drf.busroute'),
        ),
    ]
