# Generated by Django 5.0.4 on 2024-06-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0016_alter_halte_options_alter_busschedule_rute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='user', max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
