# Generated by Django 5.0.4 on 2024-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0018_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Sport', 'Sport'), ('Politic', 'Politic'), ('Heatlh', 'Heatlh')], max_length=40, null=True),
        ),
    ]
