# Generated by Django 5.0.4 on 2024-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0019_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('Umum', 'Umum'), ('Lifestyle', 'Lifestyle'), ('Sport', 'Sport'), ('Politic', 'Politic'), ('Health', 'Health')], max_length=40, null=True),
        ),
    ]
