# Generated by Django 5.0.4 on 2024-06-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0020_alter_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaktuRute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=10)),
                ('waktu_1', models.TimeField(blank=True, null=True)),
                ('waktu_2', models.TimeField(blank=True, null=True)),
                ('waktu_3', models.TimeField(blank=True, null=True)),
                ('waktu_4', models.TimeField(blank=True, null=True)),
                ('waktu_5', models.TimeField(blank=True, null=True)),
                ('waktu_6', models.TimeField(blank=True, null=True)),
                ('waktu_7', models.TimeField(blank=True, null=True)),
                ('halte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.halte')),
                ('rute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.busroute')),
            ],
        ),
    ]
