# Generated by Django 5.0.4 on 2024-06-24 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0021_wakturute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wakturute',
            name='halte',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_1',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_2',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_3',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_4',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_5',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_6',
        ),
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_7',
        ),
        migrations.AlterField(
            model_name='wakturute',
            name='rute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_waktu', to='drf.busroute'),
        ),
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_1', models.TimeField(blank=True, null=True)),
                ('waktu_2', models.TimeField(blank=True, null=True)),
                ('waktu_3', models.TimeField(blank=True, null=True)),
                ('waktu_4', models.TimeField(blank=True, null=True)),
                ('waktu_5', models.TimeField(blank=True, null=True)),
                ('waktu_6', models.TimeField(blank=True, null=True)),
                ('waktu_7', models.TimeField(blank=True, null=True)),
                ('rute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf.busroute')),
            ],
        ),
    ]
