# Generated by Django 5.0.4 on 2024-06-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0023_alter_waktu_rute_id_alter_wakturute_rute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waktu',
            name='rute_id',
        ),
        migrations.AddField(
            model_name='wakturute',
            name='waktu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_waktu', to='drf.waktu'),
        ),
        migrations.AlterField(
            model_name='wakturute',
            name='rute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waktu_id', to='drf.busroute'),
        ),
    ]
