# Generated by Django 5.0.4 on 2024-06-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0024_remove_waktu_rute_id_wakturute_waktu_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_1',
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_2',
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_3',
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_4',
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_5',
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_6',
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu_7',
        ),
        migrations.AddField(
            model_name='waktu',
            name='waktu',
            field=models.ManyToManyField(to='drf.waktu'),
        ),
    ]
