# Generated by Django 5.0.4 on 2024-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0025_remove_waktu_waktu_1_remove_waktu_waktu_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waktu',
            name='waktu_list',
            field=models.ManyToManyField(to='drf.waktu'),
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu',
        ),
        migrations.AddField(
            model_name='waktu',
            name='waktu',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
