# Generated by Django 5.0.4 on 2024-06-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0026_waktu_waktu_list_remove_waktu_waktu_waktu_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_value', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='waktu',
            name='waktu',
        ),
        migrations.AlterField(
            model_name='waktu',
            name='waktu_list',
            field=models.ManyToManyField(to='drf.time'),
        ),
    ]
