# Generated by Django 5.0.4 on 2024-06-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0027_time_remove_waktu_waktu_alter_waktu_waktu_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wakturute',
            name='waktu_id',
        ),
        migrations.DeleteModel(
            name='Waktu',
        ),
    ]
