# Generated by Django 5.0.4 on 2024-06-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0028_remove_wakturute_waktu_id_delete_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_list', models.ManyToManyField(to='drf.time')),
            ],
        ),
        migrations.AddField(
            model_name='wakturute',
            name='waktu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_waktu', to='drf.waktu'),
        ),
    ]
