# Generated by Django 5.0.4 on 2024-06-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0030_remove_waktu_waktu_list_remove_wakturute_waktu_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_list', models.ManyToManyField(to='drf.waktu')),
            ],
        ),
    ]
