# Generated by Django 5.0.4 on 2024-06-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0031_waktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='waktu',
            name='waktu',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
