# Generated by Django 5.0.4 on 2024-06-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0034_waktu_waktu_id_alter_waktu_waktu_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='wakturute',
            name='waktu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_waktu', to='drf.waktu'),
        ),
    ]
